//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiebelReposAnalyser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiebelReposAnalyser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysing objects....
        /// </summary>
        internal static string Analysing_objects {
            get {
                return ResourceManager.GetString("Analysing_objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building list....
        /// </summary>
        internal static string Building_list {
            get {
                return ResourceManager.GetString("Building_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counting code lines....
        /// </summary>
        internal static string Counting_Code_Lines {
            get {
                return ResourceManager.GetString("Counting_Code_Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV File|*.csv.
        /// </summary>
        internal static string CSV_File {
            get {
                return ResourceManager.GetString("CSV_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML File|*.html.
        /// </summary>
        internal static string HTML_File {
            get {
                return ResourceManager.GetString("HTML_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in....
        /// </summary>
        internal static string Logging_In {
            get {
                return ResourceManager.GetString("Logging_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging out....
        /// </summary>
        internal static string Logging_out {
            get {
                return ResourceManager.GetString("Logging_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preloading Siebel Users (may take time if many users)....
        /// </summary>
        internal static string Preloading_Siebel_Users {
            get {
                return ResourceManager.GetString("Preloading_Siebel_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon REPOS_application_find {
            get {
                object obj = ResourceManager.GetObject("REPOS_application_find", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REPOS_application_find_64 {
            get {
                object obj = ResourceManager.GetObject("REPOS_application_find_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REPOS_close_window_16 {
            get {
                object obj = ResourceManager.GetObject("REPOS_close_window_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REPOS_computer_delete2_16 {
            get {
                object obj = ResourceManager.GetObject("REPOS_computer_delete2_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REPOS_computer_delete2_32 {
            get {
                object obj = ResourceManager.GetObject("REPOS_computer_delete2_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REPOS_computer_internet_32 {
            get {
                object obj = ResourceManager.GetObject("REPOS_computer_internet_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REPOS_computer_ok_16 {
            get {
                object obj = ResourceManager.GetObject("REPOS_computer_ok_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REPOS_document_spreadsheet_32 {
            get {
                object obj = ResourceManager.GetObject("REPOS_document_spreadsheet_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REPOS_document_text_internet_32 {
            get {
                object obj = ResourceManager.GetObject("REPOS_document_text_internet_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REPOS_favorite_32 {
            get {
                object obj = ResourceManager.GetObject("REPOS_favorite_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REPOS_flag_green_32 {
            get {
                object obj = ResourceManager.GetObject("REPOS_flag_green_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REPOS_gear_32 {
            get {
                object obj = ResourceManager.GetObject("REPOS_gear_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REPOS_gears_32 {
            get {
                object obj = ResourceManager.GetObject("REPOS_gears_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REPOS_help2_32 {
            get {
                object obj = ResourceManager.GetObject("REPOS_help2_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REPOS_info_32 {
            get {
                object obj = ResourceManager.GetObject("REPOS_info_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REPOS_install_16 {
            get {
                object obj = ResourceManager.GetObject("REPOS_install_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REPOS_install_32 {
            get {
                object obj = ResourceManager.GetObject("REPOS_install_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REPOS_report_32 {
            get {
                object obj = ResourceManager.GetObject("REPOS_report_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REPOS_stop_32 {
            get {
                object obj = ResourceManager.GetObject("REPOS_stop_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to CSVfile.
        /// </summary>
        internal static string Save_to_CSV_file {
            get {
                return ResourceManager.GetString("Save_to_CSV_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to HTML file.
        /// </summary>
        internal static string Save_to_HTML_file {
            get {
                return ResourceManager.GetString("Save_to_HTML_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to XML file.
        /// </summary>
        internal static string Save_to_XML_file {
            get {
                return ResourceManager.GetString("Save_to_XML_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing object changes....
        /// </summary>
        internal static string Showing_Object_Changes {
            get {
                return ResourceManager.GetString("Showing_Object_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string ToggleControls_Connected {
            get {
                return ResourceManager.GetString("ToggleControls_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        internal static string ToggleControls_Not_Connected {
            get {
                return ResourceManager.GetString("ToggleControls_Not_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML File|*.xml.
        /// </summary>
        internal static string XML_File {
            get {
                return ResourceManager.GetString("XML_File", resourceCulture);
            }
        }
    }
}
